### ISSUE TITLE
"Switch on-off" automation proposal

### ISSUE THREAD

**Issue by NivenPrasad** [100Automations/futureautomations#14]
### Overview 
_What kind of repetitive thing do you have to do often and what is the benefit of automating it?_

### Ownership of Idea
- [ ] I will be working on this automation myself
- [ ] This is my idea and I need help developing it
- [ ] Free for anyone to work on this idea

### Current State 
_"As-is" most likely something manual but could be partially automated_

### Stakeholders
_Impact - who benefits and how?_

### Automation triggers (What starts it? What's it responding to?)
- _Time-based (Specify frequency (e.g. 1x/week)_
- _Event-based (e.g. someone just created a new GitHub on a repo)_

### Output 
_(What's the desired result? What do we not want to see?)_

**Comment by jafow** [comment]
this is open for grabs I can help guide on it. it might be really fun!

**Comment by akibrhast** [comment]
Would like to grab this!

**Comment by mattyweb** [comment]
Adding some background here:

The bastion works great. we use it for secure access to the DB. the client i use (Postico) can be configured to SSH tunnel so it's a seamless process to connect. Occasionally I set up a tunnel from a terminal.

I connect for 2 reasons really.

1. I'm developing/tuning a new query and want to see how it's going to perform in production on what's now approaching 7 million records.
2. I just did a release that includes a schema change and I want to run an alembic migration. Sometimes I need to undo and redo the migration.

The challenge is that the bastion as currently configured is in an auto-scaling group so it's designed to make it impossible to turn off. I can manually reconfigure the auto-scaling group but Terraform will change it back on the next push.

The solution is deceptively simple. all that's needed to fix it is to set the min number of instances to 0 instead of 1 in the auto-scaling group. However, since it's a project referenced by a project referenced by a project and there are no variables to control this that's easier said than done...

**Comment by akibrhast** [comment]
### Possible Resources
https://github.com/hackforla/311-data/tree/dev/server/terraform

**Comment by akibrhast** [comment]
More Context Regarding this as mentioned by - @jafow 

- Bastion costs are between 1-5$ month.
- The bastion runs always because we do not know when someone may want to open a db connection. The goal of this automation is to enable what you describe, on demand connections to db via bastion
- Doesn't have to be github action but the idea is that someone who needs access can launch this bastion without needing aws knowledge or keys etc
- There are surely other ways to solve this. Each will have tradeoffs. If you're into research that may be a good place to begin
- We can allow an automation (eg github actions) to create a bastion without allowing the automation to access the resources the bastion protects
- A more general problem statement might be, how can I enable secure access to resources in a private vpc (virtual private cloud) from the outside world with the lowest cost, lowest barrier to entry (ie one click and done!)

**Comment by akibrhast** [comment]
A little bit of googling based on what you last mentioned @jafow . I came upon [this](https://www.parkmycloud.com/blog/aws-asgs/)

> The conclusion of that article is basically they have a button that allows one to scale down to 0 or suspend an ASG

So what you are looking for is
1. A github trigger of type workflow-dispatch(a manual trigger)
2. With input 0 or 1
3. Use ubuntu latest
4. download aws cli
5. retrieve relevant aws keys from github secrets
6. Using aws cli and keys from github secrets
7. 0 sets the scale of ASG's to 0, turning it off
8. 1 set's the ASG to it's original initial configuration
9. done

**Comment by akibrhast** [comment]
After talking to @darpham . It seems like this is about the extent of the workflow file I am going to be using

```yaml
name: Bastion Server
on: workflow_dispatch
​
env:
  BASTION_ASG_NAME: bastion_asg
  BASTION_DESIRED: 0 #User Update
  AWS_REGION_PROD: us-west-2
  
jobs:
  bastion:
    name: Turn on/off Bastion
    runs-on: ubuntu-latest
​
    steps:
    - name: Debug Action
      description: Print the environment variables and the event payload. Useful for developing or debugging GitHub Actions.
      uses: hmarr/debug-action@v1.0.0 # https://github.com/hmarr/debug-action
​
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1 # https://github.com/aws-actions/configure-aws-credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_PROD }}
​
    - name: Scale up/down Bastion ASG
      run: |
        aws autoscaling update-auto-scaling-group \
        	--auto-scaling-group-name ${{ env.BASTION_ASG_NAME }} \
        	--desired-capacity ${{ env.BASTION_DESIRED }}

```
