### ISSUE TITLE
Replace existing issue template with new issue template

### ISSUE THREAD

**Issue by akibrhast** [100Automations/futureautomations#29]
### Overview
We need to remove the existing automation proposal template and instead point users to use the google form

### Action Items
Create a `_config.yml` file under `.github/ISSUE_TEMPLATE/` with the following code
```yml
blank_issues_enabled: true
contact_links:
  - name: Automation Proposal
    url: https://forms.gle/BJ5p8rZuYPW729KD9
    about: Automation Idea Overview
```
